### ISSUE TITLE
Default locators are broken

### ISSUE THREAD

**Issue by ntrrgc** [rickypc/robotframework-extendedselenium2library#11]
Here is a button:

```
<button>My button</button>
```

With `Selenium2Library` you can click it like this

```
Click Button     My button
```

But the same code in `ExtendedSelenium2Library` it will timeout with an error instead. 

This is because `ExtendedSelenium2Library` overrides `click_button` in such a way that instead of relying in the parent implementation of `click_button` in order to find the button, uses a new method (`_scroll_into_view_on_internet_explorer`), which never sets the `tag=` attribute in `_element_find` like the parent implementation does.

This does not affect prefixed locators (e.g. `id=myButton`).

What is `_scroll_into_view_on_internet_explorer` for?

**Comment by rickypc** [comment]
Thank you, @ntrrgc for reporting the problem. This should be fixed in version 0.9.0. Please reopen otherwise.

`_scroll_into_view_on_internet_explorer` method will scroll the element into viewport only on Internet Explorer to eliminate possible exception. I renamed this method to `_get_element_and_scroll_into_view_on_iexplore` to give better idea on its intention and fully support `_element_find` params.

**Comment by ntrrgc** [comment]
Thanks for the fix. Now it's working again! :smile:
